title: Richie Phillips | Healthcare Data Portfolio
description: Portfolio site for Richie Phillips â€” Pharmacy Technician & Data Analyst
theme: jekyll-theme-cayman
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
